export const dummyLinkedIn = {
    name: 'linkedin_enrich',
    result: {
        data: {
            about: 'Full-stack engineer with experience leading teams and owning end-to-end product architecture across AI, SaaS, and platform-scale systems. At Proof of Skill, I’ve designed and shipped features spanning governance, referral rewards, blockchain integrations, and scalable APIs, while mentoring engineers and driving delivery across web, mobile, and backend.\n' +
                '\n' +
                'Previously at SOAL, I built core flows for Beckn protocol interoperability (BPP + Provider App) and contributed to DELTA, a learner platform powering cohorts, assessments, and navigation at scale. I’ve also worked on notification systems and platform optimizations that improved reliability and speed of shipping features.\n' +
                '\n' +
                'I enjoy building products that solve real problems, collaborating with smart teams, and exploring how technology at scale can open new opportunities for people.',
            certifications: [],
            city: 'Bengaluru',
            company: 'Proof-of-Skill protocol',
            company_description: 'Proof-of-Skill Protocol is building the credit score for skills, work history, and education. Hire smarter, faster by eliminating resume screening, assignments, & background checks.',
            company_domain: 'proofofskill.org',
            company_employee_count: 11,
            company_employee_range: '2-10',
            company_industry: 'Technology, Information and Internet',
            company_linkedin_url: 'https://www.linkedin.com/company/proof-of-skill-protocol',
            company_logo_url: 'https://media.licdn.com/dms/image/v2/D560BAQHZ5snFMNunFg/company-logo_400_400/company-logo_400_400/0/1723531317083?e=1761782400&v=beta&t=hZn6SvNyb6TRHf_k2xHFftnpVA9ctUJm7BNv3dHBTD4',
            company_website: 'https://proofofskill.org',
            company_year_founded: 2024,
            connection_count: 178,
            country: 'India',
            courses: [],
            current_company_join_month: 5,
            current_company_join_year: 2024,
            current_job_duration: '1 yr 5 mos',
            educations: [Array],
            email: '',
            experiences: [Array],
            first_name: 'Niskarsh',
            follower_count: 183,
            full_name: 'Niskarsh Kumar',
            headline: 'Product Architect @ Proof-of-Skill | IIT Kanpur',
            honors_and_awards: [],
            hq_city: '',
            hq_country: '',
            hq_region: '',
            is_creator: false,
            is_influencer: false,
            is_premium: true,
            is_verified: true,
            job_title: 'Senior Product Architect',
            languages: [],
            last_name: 'Kumar',
            linkedin_url: 'https://www.linkedin.com/in/niskarsh-kumar-1a2a25133/',
            location: 'Bengaluru, Karnataka, India',
            organizations: [],
            patents: [],
            phone: '',
            profile_id: '548973770',
            profile_image_url: 'https://media.licdn.com/dms/image/v2/D4D03AQENHn_6YfMDDw/profile-displayphoto-crop_800_800/B4DZjDRdtdH4AI-/0/1755622794358?e=1761782400&v=beta&t=GQO9lkTE3UeclRIAKgb-GoyVWFTgZYgCkspyXDYe_to',
            profile_status: [Object],
            projects: [],
            public_id: 'niskarsh-kumar-1a2a25133',
            publications: [Array],
            school: 'Indian Institute of Technology, Kanpur',
            skills: 'Server Side|Blockchain|Near|Rust (Programming Language)|Amazon Web Services (AWS)|Amazon EC2|Amazon S3|Amazon Relational Database Service (RDS)|Amazon Simple Queue Service (SQS)|Amazon Simple Email Service (SES)|Amazon Route 53|Amazon Secrets Manager|Amazon CloudFront|Amazon CloudWatch|Cron Services|Smart Contracts|Blockchain Architecture|PostgreSQL|Redis|HTML5|Cascading Style Sheets (CSS)|Server Side Programming|MERN Stack|React.js|HTML|C|Microsoft Office|Programming|Project Management|Git|Github|JavaScript|Node.js|MongoDB|Java|Matlab|Microsoft Word|Microsoft PowerPoint|Microsoft Excel|Visual studio code|SQL|Adobe Photoshop|Adobe Premiere Pro|LaTeX|Python|Leadership|Public Speaking|Teamwork|Express.js|regex',
            state: 'Karnataka',
            urn: 'ACoAACC4rMoByo0JAxw4Xep2LRGmH2PYQGK_5H4',
            volunteers: []
        },
        message: 'ok'
    }
};
